name: melodium-ci

on:
  push:

jobs:
  melodium:
    uses: melodium-tech/github-actions/.github/workflows/melodium-local-distrib.yml@v0.10.0
    with:
      command: |
        run --api-report Compo.toml --input_sql mock.sql --sql_query 'SELECT * FROM users' --output_directory output --github_status true --github_project ${{ toJSON(github.repository) }} --github_sha ${{ toJSON(github.sha) }} --github_token "$GITHUB_TOKEN"
      artifact-path: 'logs/'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      melodium-api-token: ""
    permissions:
      statuses: write